apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 1        # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: example   # Labels to match pods belonging to this deployment
  template:
    metadata:
      labels:
        app: example # Labels to apply to pods created by this deployment
    spec:
      containers:
      - name: example-container
        image: siridocker-image:latest   # Docker image for your application
        ports:
        - containerPort: 8080             # Port on which your application listens
        resources:
          limits:
            cpu: "0.5"                    # Maximum CPU resources for each pod
            memory: "512Mi"               # Maximum memory resources for each pod
          requests:
            cpu: "0.2"                    # Requested CPU resources for each pod
            memory: "256Mi"               # Requested memory resources for each pod
        env:
        - name: ENVIRONMENT_VARIABLE_1    # Environment variable 1
          value: value1
        - name: ENVIRONMENT_VARIABLE_2    # Environment variable 2
          value: value2
        # Add more environment variables as needed
